project:
  type: book

book:
  title: "WS 25/26 Numerik 0 Notes"
  author: "Igor Dimitrov"
  date: "10/10/2025"
  chapters:
    # - index.qmd
    # - summary.qmd
    # - references.qmd
    - intro.qmd
    

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



